const advisors = [
  {
    profileSlug: 'jim_stone',
    publicID: '1_ipqbnk',
    salutation: 'Hi all',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Jatinder Bhogal',
    jobDescription: 'Investor',
  },
  {
    profileSlug: 'andy_river',
    publicID: '2_vjokmx',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Jay Hayden',
    jobDescription: 'Lawyer',
  },
  {
    profileSlug: 'adele_snow',
    publicID: '3_da6nnn',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Jas Hyre',
    jobDescription: 'Tax and Investment',
  },
  {
    profileSlug: 'dylan_woods',
    publicID: '4_zhebuv',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Dylan Woods',
    jobDescription: 'Director Finance',
  },

];

const artists = [
  {
    profileSlug: 'jim_stone2',
    publicID: '6_rjzion',
    salutation: 'Hi all',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Vikram Mordani',
    jobDescription: 'CTO',
  },
  {
    profileSlug: 'andy_river1',
    publicID: '7_r8ww3n',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Kapil Nananlal',
    jobDescription: 'CTO',
  },
  {
    profileSlug: 'adele_snow1',
    publicID: '8_b0ycmt',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Minck Hermans',
    jobDescription: 'CTO',
  },
  {
    profileSlug: 'dylan_woods1',
    publicID: '9_kdmblm',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Chaitanya Amin',
    jobDescription: 'CTO',
  },
];

const technologists = [
  {
    profileSlug: 'jim_stone3',
    publicID: '11_zikya4',
    salutation: 'Hi all',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Vikram Mordani',
    jobDescription: 'CTO',
  },
  {
    profileSlug: 'andy_river3',
    publicID: '12_gaaqnv',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Chaitanya Amin',
    jobDescription: 'Front End Developer',
  },
  {
    profileSlug: 'adele_snow3',
    publicID: '13_jkbktm',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Kapil Nananlal',
    jobDescription: 'CTO',
  },
  {
    profileSlug: 'dylan_woods3',
    publicID: '14_clgbev',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Minck Hermans',
    jobDescription: 'CTO',
  },
];


export default {
  advisors,
  artists,
  technologists,
};
